version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5432:5432"
    volumes:
      - .:/backend_api
    environment:
      - DATABASE_URL=postgresql+pg8000://postgres:password@localhost/postgres
      - ENV=development