version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/backend_api
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost/wardrobers_test
      - ENV=development  # You can manage this with .env files too